"""remove dq fk

Revision ID: 27063fd392e6
Revises: ae70459f671b
Create Date: 2026-10-06 17:54:20.956775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27063fd392e6'
down_revision: Union[str, None] = 'ae70459f671b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_quality_run', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('data_quality_run_run_id_fkey', 'data_quality_run', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('data_quality_run_run_id_fkey', 'data_quality_run', 'pipeline_run', ['run_id'], ['run_id'])
    op.alter_column('data_quality_run', 'run_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
