"""add standardize_run

Revision ID: ae70459f671b
Revises: 80b5f348ef59
Create Date: 2026-10-06 17:50:49.949206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae70459f671b'
down_revision: Union[str, None] = '80b5f348ef59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standardize_run',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.String(), nullable=True),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('bytes_processed', sa.Integer(), nullable=True),
    sa.Column('output_file', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_run.run_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standardize_run')
    # ### end Alembic commands ###
