"""Add synthetic master data models

Revision ID: eeed1a1f5eee
Revises: 27063fd392e6
Create Date: 2026-10-06 18:24:02.342485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeed1a1f5eee'
down_revision: Union[str, None] = '27063fd392e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synth_customer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synth_service_point',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region_code', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synth_account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['synth_customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synth_meter',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_household_id', sa.String(), nullable=False),
    sa.Column('service_point_id', sa.String(), nullable=False),
    sa.Column('tariff_code', sa.String(), nullable=True),
    sa.Column('meter_type', sa.String(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['service_point_id'], ['synth_service_point.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_household_id')
    )
    op.create_index('idx_meter_household', 'synth_meter', ['source_household_id'], unique=False)
    op.create_table('synth_contract',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('service_point_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('contract_start', sa.DateTime(), nullable=True),
    sa.Column('contract_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['synth_account.id'], ),
    sa.ForeignKeyConstraint(['service_point_id'], ['synth_service_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synth_contract')
    op.drop_index('idx_meter_household', table_name='synth_meter')
    op.drop_table('synth_meter')
    op.drop_table('synth_account')
    op.drop_table('synth_service_point')
    op.drop_table('synth_customer')
    # ### end Alembic commands ###
