"""Initial tables

Revision ID: fd5617b05b76
Revises: 
Create Date: 2026-10-06 22:39:31.060288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5617b05b76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_job',
    sa.Column('backfill_id', sa.String(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('backfill_id')
    )
    op.create_table('dlq_event',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('payload_reference', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('pipeline',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_run',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_rejected', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('data_quality_run',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=False),
    sa.Column('validity', sa.Float(), nullable=False),
    sa.Column('uniqueness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_quality_run')
    op.drop_table('pipeline_run')
    op.drop_table('pipeline')
    op.drop_table('dlq_event')
    op.drop_table('backfill_job')
    # ### end Alembic commands ###
